{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggdendro
  version: {{ version|replace("-", "_") }}

source:
  fn: ggdendro_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggdendro_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggdendro/ggdendro_{{ version }}.tar.gz
  sha256: 1940c34ddb30083a4c3bc3be98b6b466dcc78e03ac22a32088744db8bff7aa69

build:
  merge_build_host: true  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-ggplot2 >=0.9.2
  run:
    - r-base
    - r-mass
    - r-ggplot2 >=0.9.2

test:
  commands:
    - $R -e "library('ggdendro')"           # [not win]
    - "\"%R%\" -e \"library('ggdendro')\""  # [win]

about:
  home: https://github.com/andrie/ggdendro
  license: GPL-2.0-or-later
  summary: This is a set of tools for dendrograms and tree plots using 'ggplot2'.  The 'ggplot2' philosophy is to clearly separate data from the presentation. Unfortunately the plot method for dendrograms plots directly to a plot device without exposing the data. The 'ggdendro' package resolves this by making available functions
    that extract the dendrogram plot data. The package provides implementations for tree, rpart, as well as diana and agnes cluster diagrams.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
