appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pwa9OhagAbuLrMirse0bE46q4+ouvoV9Wmzlz0wVjUiaZzHKQXIjYRJwcvhTua0VOVdzNMcpl3Pf7zTlpsS14KobwHhwCVfI0T06ciMsmJe8pJFBqaGqZQwUrm0YM3dj+MA4JA43XQxZtVRTRdoZE6ORR1xzCdy7eBYH9UIOb0yZVe+KVx9W76V1LSGrNss5quGnfGOaVioxOvUGKoiD1uKErrXXE1gFPJbjD+W4rfI+Z8cKBP2WpCuYD+6LVuz09ddvMpG8rOkzqXIQ76YVMvaCIuOjavtA5uCYPgDZ38TNvIrFhwmAx6oa8b6lmcPkwgMskEIrqKfxiOYsSmG660pJDEZDT5UvXCOyM57+DWGEEQRpMcAlXKW88zatxap+mzqWm1dm1LzPbh9+V2NiOtnptCYbmoYPe00lP045wUDyNPpRamybV0hTv/jdGE4wKBjt7Zz1KVFUJCTql7h9NpqWnmAXTOAWa2sEb+gyfiadcVGe+3UWP0cM7rXikmHbd/caJiqsPYAEvdFnMqca5ptSqAQJJoPh4/A/bAUzi++PqdeNTL4ZEoQITkxTHqA4sNGAj5heiyO5a+noh/Xr9tdmF1VTAFRTBQ1IkZ3srMFAREkkd0RBXLnRZXpeJKdsXRpA5ylbEMq0ODooqpbBDKHt2gJ8vJG+/8cx5lcvtuI=
